/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import React from 'react';
import { FlaskConical, Languages, Sigma } from 'lucide-react';

export interface Video {
  title: string;
  description: string;
  videoId: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
}

export interface Project {
  title: string;
  description: string;
  tasks: string[];
}

export interface Lesson {
  name: string;
  description?: string;
  videos: Video[];
  projects: Project[];
}

export interface SubTopic {
  name: string;
  description?: string;
  lessons?: Lesson[];
  videos?: Video[];
  projects?: Project[];
}

export interface Topic {
  name: string;
  subTopics: SubTopic[];
}

export interface LearningContent {
  grade: string;
  topics: Topic[];
}

export interface CategoryWithGrades {
  name: string;
  icon: React.ComponentType<any>;
  contentByGrade: LearningContent[];
}

export const funFacts: string[] = [
  "The heart of a shrimp is located in its head.",
  "A snail can sleep for three years.",
  "The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene.",
  "Slugs have four noses.",
  "Elephants are the only animal that can't jump.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
  "A group of flamingos is called a 'flamboyance'.",
  "Honey never spoils.",
  "A crocodile cannot stick its tongue out."
];

const sciences: CategoryWithGrades = {
  name: 'Sciences',
  icon: FlaskConical,
  contentByGrade: [
    {
      grade: 'Grade 7',
      topics: [
        { name: 'General Science', subTopics: [ { name: 'Scientific Investigation', lessons: [
            { name: 'The Scientific Method', videos: [{ title: 'The Scientific Method', description: 'An introduction to the steps of scientific investigation.', videoId: 'zcavPAFiG14', level: 'Beginner' }], projects: [{ title: 'Investigate a Question', description: 'Choose a simple question and use the scientific method to investigate it.', tasks: ['Formulate a question.', 'Develop a hypothesis.', 'Design and conduct an experiment.', 'Analyze the data and draw a conclusion.'] }] },
            { name: 'Laboratory Safety', videos: [{ title: 'Lab Safety Rules', description: 'Learn the essential safety rules for the science lab.', videoId: 'MEIXRLcC6RA', level: 'Beginner' }], projects: [{ title: 'Create a Lab Safety Poster', description: 'Design a poster illustrating key lab safety rules.', tasks: ['Research common lab hazards.', 'Illustrate safety procedures.', 'Present your poster to the class.'] }] },
            { name: 'Common Laboratory Apparatus', videos: [{ title: 'Science Lab Equipment', description: 'An introduction to common laboratory apparatus and their uses.', videoId: 'a_qV6-y-S3U', level: 'Beginner' }], projects: [{ title: 'Apparatus Identification Game', description: 'Create a game to help identify and learn the uses of lab equipment.', tasks: ['Create flashcards or a digital quiz.', 'Include pictures and descriptions.', 'Challenge your classmates to play.'] }] },
            { name: 'Measurement in Science', videos: [{ title: 'Measuring Length, Mass, and Volume', description: 'Learn how to use rulers, balances, and graduated cylinders.', videoId: 'cQ_h-3G89-I', level: 'Beginner' }], projects: [{ title: 'Measure Objects in Your Home', description: 'Practice your measurement skills by measuring various objects.', tasks: ['Find five objects.', 'Measure their length, mass, and volume.', 'Record your measurements in a table.'] }] },
            { name: 'Data Collection and Presentation', videos: [{ title: 'How to Make a Data Table', description: 'Learn how to organize and present data in a table.', videoId: 'b4k9-Q1c2wY', level: 'Beginner' }], projects: [{ title: 'Survey Your Classmates', description: 'Conduct a survey and present the data in a table and graph.', tasks: ['Choose a survey topic.', 'Collect data from your classmates.', 'Create a data table and a bar graph.', 'Explain your findings.'] }] },
          ] } ] },
        { name: 'Chemistry', subTopics: [ { name: 'Mixtures, Elements and Compounds', lessons: [
            { name: 'States of Matter', videos: [{ title: 'States of Matter', description: 'An introduction to solids, liquids, and gases.', videoId: 'jmm1J2yI9tk', level: 'Beginner' }], projects: [{ title: 'Build a Model of Water Molecules', description: 'Create models showing the arrangement of water molecules in solid, liquid, and gas form.', tasks: ['Use marshmallows or other materials.', 'Build the three models.', 'Explain the differences in arrangement and movement.'] }] },
            { name: 'Separating Mixtures', videos: [{ title: 'Separating Mixtures', description: 'Learn different techniques for separating mixtures, such as filtration and evaporation.', videoId: 'fVpKlW240sI', level: 'Intermediate' }], projects: [{ title: 'Separate a Mixture of Sand and Salt', description: 'Use filtration and evaporation to separate a mixture of sand and salt.', tasks: ['Mix sand and salt.', 'Add water to dissolve the salt.', 'Filter the mixture to separate the sand.', 'Evaporate the water to recover the salt.'] }] },
            { name: 'Elements and the Periodic Table', videos: [{ title: 'The Periodic Table', description: 'An introduction to the periodic table of elements.', videoId: '0RRVV4DiA6k', level: 'Intermediate' }], projects: [{ title: 'Create an Element Superhero', description: 'Choose an element and create a superhero based on its properties.', tasks: ['Research an element.', 'Design a superhero costume and powers.', 'Create a comic strip or story.'] }] },
            { name: 'Compounds and Chemical Formulas', videos: [{ title: 'What are Compounds?', description: 'Learn about compounds and how to write chemical formulas.', videoId: 'k4y7s-b6e-c', level: 'Intermediate' }], projects: [{ title: 'Build Models of Molecules', description: 'Use molecular model kits or other materials to build models of simple compounds.', tasks: ['Choose three compounds.', 'Build models of the molecules.', 'Label the atoms and bonds.'] }] },
            { name: 'Physical and Chemical Changes', videos: [{ title: 'Physical and Chemical Changes', description: 'Learn the difference between physical and chemical changes.', videoId: '4hM_Zg96-Eo', level: 'Beginner' }], projects: [{ title: 'Identify Changes Around You', description: 'Observe and classify changes happening in your home or school.', tasks: ['Find five examples of changes.', 'Classify each as a physical or chemical change.', 'Explain your reasoning.'] }] }
          ] } ] },
        { name: 'Biology', subTopics: [ { name: 'Living Things and Their Environment', lessons: [
            { name: 'Characteristics of Living Things', videos: [{ title: '7 Characteristics of Living Things', description: 'Learn the seven characteristics that define life.', videoId: 'v_9w42gB7pA', level: 'Beginner' }], projects: [{ title: 'Living vs. Non-Living', description: 'Go on a nature walk and classify objects as living or non-living.', tasks: ['Find 10 objects.', 'Classify each as living or non-living.', 'Explain your reasoning based on the seven characteristics.'] } ] }] },
            { name: 'Classification of Living Things', videos: [{ title: 'The Five Kingdoms', description: 'An introduction to the five kingdoms of living things.', videoId: 'tsGW4s-xM4o', level: 'Intermediate' }], projects: [{ title: 'Create a Classification Chart', description: 'Create a chart showing the classification of five different organisms.', tasks: ['Choose five organisms.', 'Research their kingdom, phylum, class, order, family, genus, and species.', 'Create a chart to display the information.'] }] },
            { name: 'Ecosystems and Habitats', videos: [{ title: 'What is an Ecosystem?', description: 'Learn about the components of an ecosystem and how they interact.', videoId: 'bJEToQ49Yjc', level: 'Beginner' }], projects: [{ title: 'Build a Mini-Ecosystem', description: 'Create a self-contained ecosystem in a jar.', tasks: ['Gather soil, plants, and small insects.', 'Assemble your ecosystem in a sealed jar.', 'Observe the changes over time.'] }] },
            { name: 'Food Chains and Food Webs', videos: [{ title: 'Food Chains & Food Webs', description: 'Learn how energy flows through an ecosystem.', videoId: 'VtbSKntpGmc', level: 'Intermediate' }], projects: [{ title: 'Create a Food Web Diagram', description: 'Create a diagram of a food web for a specific habitat.', tasks: ['Choose a habitat (e.g., forest, ocean).', 'Research the organisms that live there.', 'Draw a food web showing the flow of energy.'] }] },
            { name: 'Human Impact on the Environment', videos: [{ title: 'Human Impact on the Environment', description: 'Learn about the effects of human activities on the environment.', videoId: '5eTCZ9L834s', level: 'Advanced' }], projects: [{ title: 'Reduce, Reuse, Recycle Campaign', description: 'Create a campaign to promote recycling in your school.', tasks: ['Design posters and flyers.', 'Give a presentation to your class.', 'Organize a recycling drive.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 8',
      topics: [
        { name: 'Biology', subTopics: [ { name: 'Human Body Systems', lessons: [
            { name: 'The Circulatory System', videos: [{ title: 'The Circulatory System', description: 'A detailed look at the heart, blood vessels, and blood.', videoId: 'CWFyxn0qDEU', level: 'Intermediate' }], projects: [{ title: 'Build a Model of the Heart', description: 'Create a model of the human heart showing the four chambers.', tasks: ['Research the structure of the heart.', 'Design and build a model.', 'Label the parts of the heart.', 'Explain the flow of blood through the heart.'] }] },
            { name: 'The Respiratory System', videos: [{ title: 'The Respiratory System', description: 'Learn how we breathe and how our lungs work.', videoId: 'b-pao_b3k9s', level: 'Intermediate' }], projects: [{ title: 'Build a Model Lung', description: 'Create a working model of a lung.', tasks: ['Use a bottle, balloon, and straw.', 'Assemble the model.', 'Demonstrate how the lung inflates and deflates.'] }] },
            { name: 'The Digestive System', videos: [{ title: 'The Digestive System', description: 'Follow the journey of food through the digestive system.', videoId: 's06XzaKqELk', level: 'Intermediate' }], projects: [{ title: 'Create a Digestive System Diagram', description: 'Draw and label a diagram of the human digestive system.', tasks: ['Research the organs of the digestive system.', 'Draw the diagram.', 'Label each organ and its function.'] }] },
            { name: 'The Nervous System', videos: [{ title: 'The Nervous System', description: 'An introduction to the brain, spinal cord, and nerves.', videoId: 'qPix_X-9t7E', level: 'Intermediate' }], projects: [{ title: 'Test Your Reaction Time', description: 'Design an experiment to test and compare reaction times.', tasks: ['Develop a hypothesis.', 'Design and conduct the experiment.', 'Analyze the results.', 'Draw a conclusion.'] }] },
            { name: 'The Skeletal System', videos: [{ title: 'The Skeletal System', description: 'Learn about the bones that make up our skeleton.', videoId: 'v-c68sF9K8A', level: 'Intermediate' }], projects: [{ title: 'Build a Model of a Joint', description: 'Create a model of a hinge joint, like the knee or elbow.', tasks: ['Use cardboard, string, and other materials.', 'Assemble the model.', 'Demonstrate how the joint moves.'] }] },
          ] } ] },
        { name: 'Physics', subTopics: [ { name: 'Energy', lessons: [
            { name: 'Forms of Energy', videos: [{ title: 'Forms of Energy', description: 'Learn about the different forms of energy, such as kinetic, potential, and thermal energy.', videoId: 'Q0sryf-0B-A', level: 'Beginner' }], projects: [{ title: 'Energy Scavenger Hunt', description: 'Find examples of different forms of energy in your home or school.', tasks: ['Identify five different forms of energy.', 'Take pictures or draw diagrams of each.', 'Explain how each example represents that form of energy.'] }] },
            { name: 'Energy Transformations', videos: [{ title: 'Energy Transformations', description: 'Learn how energy can be changed from one form to another.', videoId: 'x2-2T4R_d-s', level: 'Intermediate' }], projects: [{ title: 'Build a Rube Goldberg Machine', description: 'Design and build a machine that performs a simple task in a complex way, demonstrating energy transformations.', tasks: ['Design your machine.', 'Build it using everyday objects.', 'Identify the energy transformations at each step.'] }] },
            { name: 'Sources of Energy', videos: [{ title: 'Renewable and Non-Renewable Energy', description: 'Learn about different sources of energy and their impact on the environment.', videoId: 'p0p4pYSSgJc', level: 'Intermediate' }], projects: [{ title: 'Research a Renewable Energy Source', description: 'Choose a renewable energy source and create a presentation about it.', tasks: ['Research the pros and cons of the energy source.', 'Create a presentation.', 'Explain how it can be used to generate electricity.'] }] },
            { name: 'Conservation of Energy', videos: [{ title: 'The Law of Conservation of Energy', description: 'Learn that energy cannot be created or destroyed, only transformed.', videoId: 'k6e12wml-hU', level: 'Advanced' }], projects: [{ title: 'Energy Audit of Your Home', description: 'Conduct an energy audit of your home to identify ways to conserve energy.', tasks: ['Identify areas where energy is being wasted.', 'Suggest ways to reduce energy consumption.', 'Create a plan to implement your suggestions.'] }] },
            { name: 'Heat Transfer', videos: [{ title: 'Heat Transfer: Conduction, Convection, and Radiation', description: 'Learn about the three methods of heat transfer.', videoId: '9g-d6y4K49g', level: 'Intermediate' }], projects: [{ title: 'Build a Solar Oven', description: 'Design and build a solar oven to cook a simple snack.', tasks: ['Design your solar oven.', 'Build it using a cardboard box, aluminum foil, and plastic wrap.', 'Test your oven by melting chocolate or marshmallows.'] }] },
          ] }, { name: 'Forces and Motion', lessons: [
            { name: 'Introduction to Forces', videos: [{ title: 'What is a Force?', description: 'An introduction to forces and how they affect motion.', videoId: 'GvIm-qJd-48', level: 'Beginner' }], projects: [{ title: 'Push and Pull Investigation', description: 'Investigate the effects of different pushes and pulls on an object.', tasks: ['Choose an object.', 'Apply different forces to it.', 'Observe and record the changes in its motion.'] } ] }] },
            { name: 'Newton\'s Laws of Motion', videos: [{ title: 'Newton\'s Three Laws of Motion', description: 'Learn about Newton\'s three laws of motion.', videoId: 'kKKM8Y-u7ds', level: 'Intermediate' }], projects: [{ title: 'Build a Balloon Rocket', description: 'Build a rocket powered by a balloon to demonstrate Newton\'s third law.', tasks: ['Design and build your rocket.', 'Launch it and observe its motion.', 'Explain how it demonstrates Newton\'s third law.'] }] },
            { name: 'Friction and Gravity', videos: [{ title: 'Friction and Gravity', description: 'Learn about the forces of friction and gravity.', videoId: '7-6-p2xnfYc', level: 'Intermediate' }], projects: [{ title: 'Investigate Friction', description: 'Design an experiment to investigate how friction affects the motion of an object.', tasks: ['Develop a hypothesis.', 'Design and conduct the experiment.', 'Analyze the results.', 'Draw a conclusion.'] }] },
            { name: 'Simple Machines', videos: [{ title: 'Simple Machines', description: 'Learn about the six types of simple machines.', videoId: 'fvOmaf2GfCY', level: 'Beginner' }], projects: [{ title: 'Design a Compound Machine', description: 'Design a machine that uses at least two simple machines to perform a task.', tasks: ['Brainstorm ideas.', 'Draw a diagram of your machine.', 'Explain how it works.'] }] },
            { name: 'Work, Power, and Energy', videos: [{ title: 'Work, Energy, and Power', description: 'Learn the relationship between work, power, and energy.', videoId: '8-PjAy0gG2s', level: 'Advanced' }], projects: [{ title: 'Calculate Your Power', description: 'Calculate your own power by running up a flight of stairs.', tasks: ['Measure the height of the stairs.', 'Time yourself running up the stairs.', 'Calculate the work you did and your power output.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 9',
      topics: [
        { name: 'Biology', subTopics: [ { name: 'The Cell', lessons: [
            { name: 'Introduction to the Cell', videos: [{ title: 'Introduction to the Cell', description: 'An overview of the basic unit of life.', videoId: '8IlzKri08kk', level: 'Beginner' }], projects: [{ title: 'Compare Plant and Animal Cells', description: 'Create a diagram or model comparing plant and animal cells.', tasks: ['Research the organelles in each type of cell.', 'Draw or build models of each.', 'Label the organelles.', 'Highlight the differences between the two.'] }] },
            { name: 'Microscopy and Cell Observation', videos: [{ title: 'How to Use a Microscope', description: 'Learn the parts of a microscope and how to use it to observe cells.', videoId: 'tVcEEwWffus', level: 'Intermediate' }], projects: [{ title: 'Observe Onion Cells', description: 'Prepare a slide and observe onion cells under a microscope.', tasks: ['Prepare a wet mount of an onion peel.', 'Observe the cells under low and high power.', 'Draw and label what you see.'] }] },
            { name: 'Cell Organelles and Functions', videos: [{ title: 'A Tour of the Cell', description: 'A detailed look at the organelles inside a cell and their functions.', videoId: '1Z9pqST72is', level: 'Intermediate' }], projects: [{ title: 'Create a 3D Cell Model', description: 'Build a 3D model of a plant or animal cell.', tasks: ['Choose a cell type.', 'Use various materials to represent the organelles.', 'Label each organelle.', 'Present your model to the class.'] }] },
            { name: 'Cell Division (Mitosis)', videos: [{ title: 'Mitosis: Splitting Up is Complicated', description: 'An animated explanation of the process of mitosis.', videoId: 'f-ldPgEfAHI', level: 'Advanced' }], projects: [{ title: 'Create a Mitosis Flipbook', description: 'Create a flipbook animating the stages of mitosis.', tasks: ['Draw the stages of mitosis on separate cards.', 'Assemble the cards into a flipbook.', 'Demonstrate the process of cell division.'] }] },
            { name: 'Tissues, Organs, and Organ Systems', videos: [{ title: 'Levels of Organization', description: 'Learn how cells, tissues, organs, and organ systems work together.', videoId: 'ZRFykdf4kjk', level: 'Advanced' }], projects: [{ title: 'Research an Organ System', description: 'Choose an organ system and create a presentation about it.', tasks: ['Research the organs and their functions.', 'Create a presentation.', 'Explain how the system works with other systems.'] }] },
          ] }, { name: 'Genetics and Evolution', lessons: [
            { name: 'Introduction to Genetics', videos: [{ title: 'What is Genetics?', description: 'An introduction to the study of heredity and variation.', videoId: 'c_p2b-0l3-0', level: 'Beginner' }], projects: [{ title: 'Family Tree of Traits', description: 'Trace a specific trait (like eye color) through your family.', tasks: ['Choose a trait.', 'Interview family members.', 'Create a family tree showing the trait.', 'Analyze the inheritance pattern.'] }] },
            { name: 'DNA, Genes, and Chromosomes', videos: [{ title: 'DNA, Chromosomes, Genes, and Traits', description: 'An explanation of the relationship between these key genetic components.', videoId: '8m6hHRlKwxY', level: 'Intermediate' }], projects: [{ title: 'Build a DNA Model', description: 'Create a model of a DNA double helix.', tasks: ['Use candy, craft supplies, or a kit.', 'Label the parts of the model (nucleotides, base pairs).', 'Explain how DNA stores genetic information.'] }] },
            { name: 'Mendelian Genetics', videos: [{ title: 'Mendel\'s Peas', description: 'Learn about Gregor Mendel and his experiments with pea plants.', videoId: 'Mehz7tCxjSE', level: 'Intermediate' }], projects: [{ title: 'Punnett Square Practice', description: 'Use Punnett squares to predict the outcomes of genetic crosses.', tasks: ['Learn how to set up a Punnett square.', 'Solve a series of practice problems.', 'Explain the concepts of dominant and recessive alleles.'] }] },
            { name: 'Natural Selection', videos: [{ title: 'What is Natural Selection?', description: 'An explanation of the process of natural selection.', videoId: '0-04v9hFv_E', level: 'Advanced' }], projects: [{ title: 'Simulate Natural Selection', description: 'Design a simulation to demonstrate how natural selection works.', tasks: ['Use beads, paper, or other materials to represent a population.', 'Introduce an environmental change.', 'Observe how the population changes over generations.'] }] },
            { name: 'Evidence for Evolution', videos: [{ title: 'Evidence of Evolution', description: 'Learn about the different types of evidence that support the theory of evolution.', videoId: 'lIEoO5KdPvg', level: 'Advanced' }], projects: [{ title: 'Create a Fossil Record', description: 'Create a fictional fossil record to show how a species has changed over time.', tasks: ['Design a fictional organism.', 'Draw a series of fossils showing its evolution.', 'Explain the changes you have depicted.'] }] }
          ] } ] },
        { name: 'Chemistry', subTopics: [ { name: 'Acids, Bases, and Salts', lessons: [
            { name: 'Properties of Acids and Bases', videos: [{ title: 'Acids and Bases Introduction', description: 'Learn the basic properties of acids and bases.', videoId: 'A_iH5-bI7zI', level: 'Beginner' }], projects: [{ title: 'Test Household Substances', description: 'Test common household substances to see if they are acidic or basic.', tasks: ['Use litmus paper or a natural indicator.', 'Test substances like lemon juice, soap, and vinegar.', 'Record your results in a table.'] } ] }] },
            { name: 'The pH Scale', videos: [{ title: 'What is the pH Scale?', description: 'An explanation of the pH scale and how it measures acidity.', videoId: 'pQOa3bbvL1s', level: 'Intermediate' }], projects: [{ title: 'Create a pH Rainbow', description: 'Use a universal indicator to create a rainbow of different pH values.', tasks: ['Use a variety of acidic and basic solutions.', 'Add universal indicator to each.', 'Arrange them in order of pH to create a rainbow.'] }] },
            { name: 'Neutralization Reactions', videos: [{ title: 'Neutralization Reactions', description: 'Learn what happens when an acid and a base react.', videoId: 'P5t2h-knj7s', level: 'Intermediate' }], projects: [{ title: 'Make Your Own Volcano', description: 'Create a chemical volcano using baking soda (a base) and vinegar (an acid).', tasks: ['Build a volcano model.', 'Mix baking soda and vinegar inside.', 'Observe the neutralization reaction.'] }] },
            { name: 'Indicators', videos: [{ title: 'Acid-Base Indicators', description: 'Learn how indicators work and how to make your own.', videoId: 'jHm-kGUj2oY', level: 'Beginner' }], projects: [{ title: 'Make Red Cabbage Indicator', description: 'Make your own pH indicator from red cabbage.', tasks: ['Boil red cabbage to extract the juice.', 'Test the indicator with different household substances.', 'Observe the color changes.'] }] },
            { name: 'Salts', videos: [{ title: 'What are Salts?', description: 'Learn about salts and how they are formed.', videoId: 'DEa5_pG8g5g', level: 'Advanced' }], projects: [{ title: 'Grow Your Own Crystals', description: 'Grow salt crystals from a supersaturated solution.', tasks: ['Create a supersaturated salt solution.', 'Suspend a string in the solution.', 'Observe the crystal growth over several days.'] }] }
          ]
        }
      ]
    }
  ]
};

const languages: CategoryWithGrades = {
  name: 'Languages',
  icon: Languages,
  contentByGrade: [
    {
      grade: 'Grade 7',
      topics: [
        { name: 'English Language', subTopics: [ { name: 'Functional Writing', lessons: [
            { name: 'Formal Emails', videos: [{ title: 'How to Write a Formal Email', description: 'Learn the structure and etiquette of writing formal emails.', videoId: 'D8_0w3-Gg4U', level: 'Beginner' }], projects: [{ title: 'Write a Formal Email', description: 'Compose a formal email to a teacher or official.', tasks: ['Choose a scenario.', 'Draft the email, paying attention to format.', 'Review and edit for clarity and tone.', 'Send the email (or a draft).'] }] },
            { name: 'Writing Minutes of a Meeting', videos: [{ title: 'How to Write Meeting Minutes', description: 'Learn the proper format and content for meeting minutes.', videoId: 'Uii-aC00O_c', level: 'Intermediate' }], projects: [{ title: 'Take Minutes for a Mock Meeting', description: 'Participate in a mock meeting and take the official minutes.', tasks: ['Prepare an agenda.', 'Take notes during the meeting.', 'Write the minutes in the correct format.', 'Share the minutes with the group.'] }] },
            { name: 'Writing a CV (Curriculum Vitae)', videos: [{ title: 'How to Write a Great CV', description: 'Learn how to create a professional CV.', videoId: 'pvFso4Xh41M', level: 'Intermediate' }], projects: [{ title: 'Create Your Own CV', description: 'Draft a CV for a fictional person or for yourself.', tasks: ['Choose a template.', 'Fill in the relevant sections.', 'Tailor the CV for a specific job.', 'Get feedback on your CV.'] }] },
            { name: 'Writing Reports', videos: [{ title: 'How to Write a Report', description: 'Learn the structure and key elements of a formal report.', videoId: 'V-yW-r5fA-A', level: 'Intermediate' }], projects: [{ title: 'Write a Report on a School Event', description: 'Write a formal report on a recent school event.', tasks: ['Gather information about the event.', 'Outline the report structure.', 'Write the report.', 'Proofread and edit your work.'] }] },
            { name: 'Writing Memos', videos: [{ title: 'How to Write a Memo', description: 'Learn the purpose and format of a memorandum.', videoId: '1c4h6p_GjA4', level: 'Beginner' }], projects: [{ title: 'Write a Memo to Your Classmates', description: 'Write a memo informing your classmates of an upcoming event.', tasks: ['Choose a topic.', 'Write the memo in the correct format.', 'Distribute the memo to your classmates.'] }] },
          ] }, { name: 'Grammar and Usage', lessons: [
            { name: 'Parts of Speech', videos: [{ title: 'The 8 Parts of Speech', description: 'Learn about nouns, pronouns, verbs, adjectives, adverbs, prepositions, conjunctions, and interjections.', videoId: 'A_Pl9G4_iks', level: 'Beginner' }], projects: [{ title: 'Parts of Speech Story', description: 'Write a short story that includes all eight parts of speech.', tasks: ['Write a one-page story.', 'Highlight and label an example of each part of speech.', 'Share your story with the class.'] }] },
            { name: 'Sentence Structure', videos: [{ title: 'Sentence Structure', description: 'Learn about the different types of sentences: simple, compound, complex, and compound-complex.', videoId: 'D9Wn_4i-6jA', level: 'Intermediate' }], projects: [{ title: 'Sentence Scramble', description: 'Create a set of scrambled sentences for a partner to unscramble.', tasks: ['Write five sentences of different types.', 'Cut them up into individual words.', 'Have a partner unscramble them.'] }] },
            { name: 'Punctuation', videos: [{ title: 'Punctuation Explained', description: 'A guide to using commas, periods, apostrophes, and other punctuation marks correctly.', videoId: 'yhbMg4i-g9g', level: 'Beginner' }], projects: [{ title: 'Punctuate a Paragraph', description: 'Take an unpunctuated paragraph and add the correct punctuation.', tasks: ['Find or write a paragraph without punctuation.', 'Add the necessary punctuation marks.', 'Explain your choices.'] }] },
            { name: 'Tenses', videos: [{ title: 'Introduction to Verb Tenses', description: 'Learn about the past, present, and future tenses.', videoId: '4h_yMMaG-sU', level: 'Intermediate' }], projects: [{ title: 'Tense Transformation', description: 'Rewrite a paragraph in a different tense.', tasks: ['Choose a paragraph.', 'Rewrite it, changing the tense from past to present, or vice versa.', 'Share your rewritten paragraph with a partner.'] }] },
            { name: 'Common Grammatical Errors', videos: [{ title: '10 Common Grammatical Errors', description: 'Learn how to avoid common grammatical mistakes.', videoId: 'qE-cAYQ0yKg', level: 'Intermediate' }], projects: [{ title: 'Proofreading Practice', description: 'Find and correct the grammatical errors in a piece of writing.', tasks: ['Find a short article or story with errors.', 'Identify and correct the errors.', 'Explain the corrections you made.'] }] }
          ] } ] },
        { name: 'Literature', subTopics: [ { name: 'Figurative Language', lessons: [
            { name: 'Similes and Metaphors', videos: [{ title: 'Similes and Metaphors', description: 'Learn the difference between similes and metaphors.', videoId: 'uoSBVNUO2aA', level: 'Beginner' }], projects: [{ title: 'Create a Poem', description: 'Write a poem using similes and metaphors.', tasks: ['Choose a topic for your poem.', 'Brainstorm a list of similes and metaphors.', 'Write and revise your poem.'] } ] }] },
            { name: 'Personification', videos: [{ title: 'Personification for Kids', description: 'An explanation of personification with examples.', videoId: '29_A82A1-3M', level: 'Beginner' }], projects: [{ title: 'Write a Story', description: 'Write a short story in which an inanimate object is the main character.', tasks: ['Choose an object.', 'Brainstorm its personality and motivations.', 'Write and revise your story.'] }] },
            { name: 'Hyperbole', videos: [{ title: 'Hyperbole in Songs', description: 'Learn about hyperbole by listening to examples in popular songs.', videoId: 'R4-c48s4-wM', level: 'Intermediate' }], projects: [{ title: 'Create a Tall Tale', description: 'Write a tall tale that uses hyperbole for comedic effect.', tasks: ['Brainstorm an exaggerated story.', 'Use hyperbole to make it as funny as possible.', 'Share your story with the class.'] }] },
            { name: 'Idioms', videos: [{ title: '20 Common English Idioms', description: 'Learn the meanings of 20 common English idioms.', videoId: 'kXg_36w23-8', level: 'Intermediate' }], projects: [{ title: 'Illustrate an Idiom', description: 'Choose an idiom and create a literal illustration of it.', tasks: ['Choose an idiom.', 'Draw a picture that shows the literal meaning of the words.', 'Explain the figurative meaning of the idiom.'] }] },
            { name: 'Onomatopoeia', videos: [{ title: 'Onomatopoeia for Kids', description: 'Learn about onomatopoeia with fun examples.', videoId: 'f1b5kCv_e8c', level: 'Beginner' }], projects: [{ title: 'Create a Sound Map', description: 'Go on a listening walk and create a map of the sounds you hear.', tasks: ['Find a place to sit and listen.', 'Write down all the sounds you hear.', 'Use onomatopoeia to describe the sounds.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 8',
      topics: [
        { name: 'English Language', subTopics: [ { name: 'Creative Writing', lessons: [
            { name: 'Poetry', videos: [{ title: 'Introduction to Poetry', description: 'Learn about the different forms and techniques of poetry.', videoId: 'JwhouCNq-Fc', level: 'Intermediate' }], projects: [{ title: 'Write a Haiku', description: 'Compose a haiku about a topic of your choice.', tasks: ['Learn the 5-7-5 syllable structure.', 'Brainstorm ideas.', 'Write and revise your haiku.', 'Share your poem with others.'] }] },
            { name: 'Short Story Writing', videos: [{ title: 'How to Write a Short Story', description: 'Learn the elements of a short story, including plot, character, and setting.', videoId: 'n2R2C_2i44U', level: 'Intermediate' }], projects: [{ title: 'Write a Short Story', description: 'Write a short story on a topic of your choice.', tasks: ['Brainstorm ideas.', 'Develop your characters and plot.', 'Write the story.', 'Revise and edit your work.'] }] },
            { name: 'Writing Dialogues and Scripts', videos: [{ title: 'How to Write a Scene', description: 'Learn how to write a compelling scene with dialogue and action.', videoId: 'g8gt4a82f4c', level: 'Advanced' }], projects: [{ title: 'Write a Short Scene', description: 'Write a one-page scene with two characters.', tasks: ['Develop your characters.', 'Write the dialogue and action.', 'Format the scene as a script.', 'Perform the scene with a partner.'] }] },
            { name: 'Descriptive Writing', videos: [{ title: 'Show, Don\'t Tell', description: 'Learn the art of descriptive writing.', videoId: 'vN5aGukJ8aM', level: 'Intermediate' }], projects: [{ title: 'Describe a Place', description: 'Write a detailed description of a place, real or imagined.', tasks: ['Choose a place.', 'Brainstorm sensory details.', 'Write a descriptive paragraph.', 'Share your description with a partner.'] }] },
            { name: 'Narrative Writing', videos: [{ title: 'The Hero\'s Journey', description: 'Learn about the classic story structure of the hero\'s journey.', videoId: 'Hhk4N9A0oCA', level: 'Advanced' }], projects: [{ title: 'Outline a Hero\'s Journey', description: 'Create an outline for a story that follows the hero\'s journey.', tasks: ['Choose a hero.', 'Outline the stages of their journey.', 'Present your story idea to the class.'] }] },
          ] }, { name: 'Reading Comprehension and Analysis', lessons: [
            { name: 'Identifying the Main Idea', videos: [{ title: 'Finding the Main Idea', description: 'Learn how to identify the main idea of a text.', videoId: 'Z9-c5-OP_mQ', level: 'Beginner' }], projects: [{ title: 'Main Idea Detective', description: 'Read a short story and identify the main idea and supporting details.', tasks: ['Read a short story.', 'Identify the main idea.', 'List three supporting details.', 'Explain how the details support the main idea.'] }] },
            { name: 'Making Inferences', videos: [{ title: 'Making Inferences', description: 'Learn how to make inferences based on textual evidence.', videoId: '21hM2oB-1qM', level: 'Intermediate' }], projects: [{ title: 'Character Inference', description: 'Read a short story and make inferences about a character\'s personality.', tasks: ['Read a short story.', 'Choose a character.', 'Make three inferences about their personality.', 'Provide textual evidence to support your inferences.'] }] },
            { name: 'Understanding Figurative Language', videos: [{ title: 'Figurative Language', description: 'Learn about similes, metaphors, personification, and other types of figurative language.', videoId: '4h_yMMaG-sU', level: 'Intermediate' }], projects: [{ title: 'Figurative Language Hunt', description: 'Find examples of figurative language in a poem or song.', tasks: ['Choose a poem or song.', 'Identify five examples of figurative language.', 'Explain the meaning of each example.'] }] },
            { name: 'Analyzing Character and Plot', videos: [{ title: 'Plot and Character', description: 'Learn how to analyze the plot and characters in a story.', videoId: 'Y-1K9T4yC4A', level: 'Advanced' }], projects: [{ title: 'Character Analysis Essay', description: 'Write an essay analyzing a character from a book you have read.', tasks: ['Choose a character.', 'Analyze their traits, motivations, and development.', 'Write a one-page essay.', 'Use textual evidence to support your analysis.'] }] },
            { name: 'Comparing and Contrasting Texts', videos: [{ title: 'Compare and Contrast', description: 'Learn how to compare and contrast two different texts.', videoId: 'a-Q24-m9SjA', level: 'Intermediate' }], projects: [{ title: 'Book vs. Movie', description: 'Compare and contrast a book with its movie adaptation.', tasks: ['Choose a book that has been made into a movie.', 'Read the book and watch the movie.', 'Create a Venn diagram comparing and contrasting the two.', 'Write a paragraph summarizing your findings.'] }] }
          ] } ] },
        { name: 'Literature', subTopics: [ { name: 'Mythology and Folklore', lessons: [
            { name: 'Introduction to Mythology', videos: [{ title: 'What is a Myth?', description: 'An introduction to the world of myths and legends.', videoId: 'k4sAk3Iu-fM', level: 'Beginner' }], projects: [{ title: 'Create Your Own Myth', description: 'Write a short myth that explains a natural phenomenon.', tasks: ['Choose a natural phenomenon (e.g., thunder, rainbows).', 'Create gods, goddesses, and heroes.', 'Write a myth to explain it.'] } ] }] },
            { name: 'Greek and Roman Mythology', videos: [{ title: 'The Gods and Goddesses of Olympus', description: 'An overview of the major Greek and Roman deities.', videoId: 'eJCm8W5RZes', level: 'Intermediate' }], projects: [{ title: 'Mythological Creature Profile', description: 'Research a creature from Greek or Roman mythology and create a profile about it.', tasks: ['Choose a creature (e.g., Minotaur, Medusa).', 'Research its origins, appearance, and stories.', 'Create a profile with illustrations.'] }] },
            { name: 'African Folklore', videos: [{ title: 'Anansi the Spider', description: 'Listen to a famous West African folktale about Anansi the trickster.', videoId: '1f_3-7_B-8M', level: 'Beginner' }], projects: [{ title: 'Retell a Folktale', description: 'Choose a folktale from an African culture and retell it in your own words.', tasks: ['Research and choose a folktale.', 'Write a summary of the story.', 'Create illustrations for your retelling.'] }] },
            { name: 'Archetypes in Myths', videos: [{ title: 'What is an Archetype?', description: 'Learn about common character archetypes found in myths and stories.', videoId: 'a-Q24-m9SjA', level: 'Advanced' }], projects: [{ title: 'Identify Archetypes', description: 'Identify character archetypes in a modern movie or book.', tasks: ['Choose a movie or book.', 'Identify the hero, mentor, trickster, and other archetypes.', 'Explain how the characters fit these roles.'] }] },
            { name: 'Modern Mythology', videos: [{ title: 'Superhero Mythology', description: 'Explore how superhero stories are a form of modern mythology.', videoId: 'Uv2-8-p-4-c-8', level: 'Advanced' }], projects: [{ title: 'Create Your Own Superhero', description: 'Create a new superhero with their own origin story and powers.', tasks: ['Brainstorm a superhero concept.', 'Design their costume and powers.', 'Write their origin story.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 9',
      topics: [
        { name: 'English Language', subTopics: [ { name: 'Public Speaking', lessons: [
            { name: 'Presentations', videos: [{ title: 'How to Give a Great Presentation', description: 'Tips and tricks for delivering a confident and engaging presentation.', videoId: 'eIho2S0ZahI', level: 'Intermediate' }], projects: [{ title: 'Prepare a 2-Minute Speech', description: 'Prepare and deliver a short speech on a topic you are passionate about.', tasks: ['Choose a topic.', 'Outline your speech.', 'Write the speech.', 'Practice your delivery.'] }] },
            { name: 'Debating Skills', videos: [{ title: 'How to Debate', description: 'Learn the basics of formal debating.', videoId: 'VvN2k1z-sfs', level: 'Intermediate' }], projects: [{ title: 'Hold a Class Debate', description: 'Participate in a formal debate on a current issue.', tasks: ['Research the topic.', 'Prepare your arguments.', 'Participate in the debate.', 'Reflect on the experience.'] }] },
            { name: 'The Art of Persuasion', videos: [{ title: 'The 3 Methods of Persuasion', description: 'Learn about ethos, pathos, and logos.', videoId: 'oKtQEnS5H4A', level: 'Advanced' }], projects: [{ title: 'Write a Persuasive Speech', description: 'Write a speech to persuade your audience to take a particular action.', tasks: ['Choose a topic.', 'Use ethos, pathos, and logos to build your argument.', 'Write the speech.', 'Deliver the speech to the class.'] }] },
            { name: 'Body Language and Non-verbal Cues', videos: [{ title: 'The Power of Body Language', description: 'Learn how to use body language to improve your communication skills.', videoId: 'cFLjudWTuGQ', level: 'Intermediate' }], projects: [{ title: 'Analyze a Famous Speech', description: 'Analyze the body language of a famous speaker.', tasks: ['Choose a speech.', 'Watch the speech and take notes on the speaker\'s body language.', 'Present your analysis to the class.'] }] },
            { name: 'Handling Questions and Answers', videos: [{ title: 'How to Handle Q&A Sessions', description: 'Learn how to effectively answer questions from the audience.', videoId: 'BPSr0eE2p3E', level: 'Advanced' }], projects: [{ title: 'Practice a Q&A Session', description: 'Prepare and practice a Q&A session on a topic of your choice.', tasks: ['Choose a topic.', 'Prepare for potential questions.', 'Practice answering questions with a partner.'] }] },
          ] } ] },
        { name: 'Literature', subTopics: [ { name: 'Literature and Film Analysis', lessons: [
            { name: 'Introduction to Literary Analysis', videos: [{ title: 'How to Analyze Literature', description: 'A beginner\'s guide to literary analysis.', videoId: 'f-w-L_u_i-E', level: 'Beginner' }], projects: [{ title: 'Analyze a Short Story', description: 'Choose a short story and write a brief analysis of it.', tasks: ['Read a short story.', 'Identify the key literary elements.', 'Write a one-page analysis.', 'Discuss your analysis with a partner.'] }] },
            { name: 'Analyzing Themes and Symbols', videos: [{ title: 'Themes and Symbols', description: 'Learn how to identify and analyze themes and symbols in literature.', videoId: '4-19s-7e-c', level: 'Intermediate' }], projects: [{ title: 'Thematic Analysis of a Poem', description: 'Choose a poem and analyze its central theme.', tasks: ['Read a poem.', 'Identify the main theme.', 'Find examples of symbols and imagery that support the theme.', 'Write a paragraph explaining your analysis.'] }] },
            { name: 'Character Analysis', videos: [{ title: 'How to Analyze a Character', description: 'A guide to analyzing fictional characters.', videoId: 't-q-9-8-g-o', level: 'Intermediate' }], projects: [{ title: 'Character Profile', description: 'Create a detailed profile of a character from a book or movie.', tasks: ['Choose a character.', 'Analyze their personality, motivations, and relationships.', 'Create a character profile.', 'Present your profile to the class.'] }] },
            { name: 'Introduction to Film Analysis', videos: [{ title: 'How to Analyze a Film', description: 'Learn the basics of film analysis, including cinematography and editing.', videoId: 's-p-g-0-c-4', level: 'Advanced' }], projects: [{ title: 'Analyze a Movie Scene', description: 'Choose a scene from a movie and analyze its cinematic techniques.', tasks: ['Choose a scene.', 'Analyze the use of camera angles, lighting, and sound.', 'Write a short analysis of the scene.', 'Share your analysis with the class.'] }] },
            { name: 'Comparing Books and Their Film Adaptations', videos: [{ title: 'Book vs. Movie', description: 'A look at the challenges and opportunities of adapting books to film.', videoId: 'g-w-p-4-c-8', level: 'Intermediate' }], projects: [{ title: 'Adaptation Review', description: 'Write a review of a film adaptation of a book.', tasks: ['Read a book and watch its film adaptation.', 'Compare and contrast the two.', 'Write a review discussing the strengths and weaknesses of the adaptation.'] }] }
          ] }, { name: 'World Literature', lessons: [
            { name: 'Introduction to World Literature', videos: [{ title: 'What is World Literature?', description: 'An exploration of the concept of world literature.', videoId: '4-19s-7e-c', level: 'Beginner' }], projects: [{ title: 'Create a World Literature Map', description: 'Create a map that shows the origins of different literary works.', tasks: ['Choose five literary works from different countries.', 'Mark their origins on a world map.', 'Write a brief summary of each work.'] } ] }] },
            { name: 'African Literature', videos: [{ title: 'Things Fall Apart by Chinua Achebe', description: 'An analysis of one of the most important works of African literature.', videoId: 'p-t-g-0-c-4', level: 'Advanced' }], projects: [{ title: 'Research an African Author', description: 'Choose an African author and create a presentation about their life and work.', tasks: ['Choose an author.', 'Research their biography and major works.', 'Create a presentation.', 'Share your findings with the class.'] }] },
            { name: 'Latin American Literature', videos: [{ title: 'One Hundred Years of Solitude by Gabriel Garcia Marquez', description: 'An introduction to magical realism and one of its most famous examples.', videoId: 't-q-9-8-g-o', level: 'Advanced' }], projects: [{ title: 'Explore Magical Realism', description: 'Write a short story that incorporates elements of magical realism.', tasks: ['Read examples of magical realism.', 'Brainstorm a story idea.', 'Write and revise your story.'] }] },
            { name: 'Asian Literature', videos: [{ title: 'The Tale of Genji by Murasaki Shikibu', description: 'Learn about what is considered the world\'s first novel.', videoId: 's-p-g-0-c-4', level: 'Intermediate' }], projects: [{ title: 'Create a Haiku Collection', description: 'Write a collection of haikus inspired by Japanese nature and culture.', tasks: ['Learn the 5-7-5 syllable structure.', 'Write at least five haikus.', 'Illustrate your poems.'] }] },
            { name: 'European Literature', videos: [{ title: 'Don Quixote by Miguel de Cervantes', description: 'An introduction to one of the most influential works of Western literature.', videoId: 'g-w-p-4-c-8', level: 'Intermediate' }], projects: [{ title: 'Modernize a Classic', description: 'Choose a classic European literary work and create a modern adaptation of it.', tasks: ['Choose a classic work.', 'Brainstorm a modern setting and characters.', 'Write a short story or script for your adaptation.'] }] }
          ]
        }
      ]
    }
  ]
};

const math: CategoryWithGrades = {
  name: 'Math',
  icon: Sigma,
  contentByGrade: [
    {
      grade: 'Grade 7',
      topics: [
        { name: 'Algebra & Number Theory', subTopics: [ { name: 'Numbers', lessons: [
            { name: 'Types of Numbers', videos: [{ title: 'Types of Numbers', description: 'An overview of integers, rational numbers, and irrational numbers.', videoId: 'N02M2s2926A', level: 'Beginner' }], projects: [{ title: 'Create a Number Line', description: 'Create a visual representation of different types of numbers on a number line.', tasks: ['Draw a number line.', 'Mark integers, fractions, and decimals.', 'Explain the relationships between the numbers.', 'Present your number line to the class.'] }] },
            { name: 'Fractions and Decimals', videos: [{ title: 'Fractions, Decimals, and Percentages', description: 'Learn how to convert between fractions, decimals, and percentages.', videoId: 'lqB4n-Vgr3g', level: 'Beginner' }], projects: [{ title: 'Recipe Conversion', description: 'Convert a recipe to serve a larger or smaller number of people.', tasks: ['Choose a recipe.', 'Decide on a new serving size.', 'Convert the ingredient amounts.', 'Share the new recipe with the class.'] }] },
            { name: 'Squares and Square Roots', videos: [{ title: 'Squares and Square Roots', description: 'An introduction to squares and square roots.', videoId: 'g-kf9Wk9u-c', level: 'Beginner' }], projects: [{ title: 'Create a Square Root Table', description: 'Create a table of squares and square roots for numbers 1-20.', tasks: ['Calculate the square of each number.', 'Calculate the square root of each number.', 'Present your table to the class.'] }] },
            { name: 'Ratios and Proportions', videos: [{ title: 'Ratios and Proportions', description: 'Learn how to work with ratios and proportions.', videoId: 'GO_p9w6a_zY', level: 'Intermediate' }], projects: [{ title: 'Scale Drawing', description: 'Create a scale drawing of your classroom or bedroom.', tasks: ['Measure the dimensions of the room.', 'Choose a scale.', 'Create the scale drawing.', 'Label the dimensions.'] }] },
            { name: 'Percentages', videos: [{ title: 'What is a Percentage?', description: 'An introduction to percentages and how to calculate them.', videoId: 'WYWPuG-wAA8', level: 'Beginner' }], projects: [{ title: 'Calculate Discounts', description: 'Calculate the sale price of items with different discounts.', tasks: ['Choose five items.', 'Calculate the sale price with a 10%, 20%, and 50% discount.', 'Present your findings to the class.'] }] },
          ] } ] },
        { name: 'Geometry & Measurement', subTopics: [ { name: 'Geometry and Measurement', lessons: [
            { name: 'Lines and Angles', videos: [{ title: 'Types of Angles', description: 'Learn about acute, obtuse, right, and straight angles.', videoId: 'dgTr2v1gEEc', level: 'Beginner' }], projects: [{ title: 'Angle Hunt', description: 'Find and identify different types of angles in your school or home.', tasks: ['Find examples of each type of angle.', 'Take pictures or draw them.', 'Label each angle with its type.'] }] },
            { name: 'Triangles and Quadrilaterals', videos: [{ title: 'Classifying Triangles and Quadrilaterals', description: 'Learn how to classify triangles and quadrilaterals based on their sides and angles.', videoId: 'mLeNaZcy-hE', level: 'Intermediate' }], projects: [{ title: 'Shape Collage', description: 'Create a collage using different types of triangles and quadrilaterals.', tasks: ['Cut out various shapes from colored paper.', 'Arrange them into a creative design.', 'Label the different types of shapes you used.'] }] },
            { name: 'Circles', videos: [{ title: 'Introduction to Circles', description: 'Learn about the parts of a circle, including the radius, diameter, and circumference.', videoId: 'O-cawByg2aA', level: 'Beginner' }], projects: [{ title: 'Measure Circular Objects', description: 'Find circular objects and measure their radius, diameter, and circumference.', tasks: ['Find five circular objects.', 'Measure the radius and diameter.', 'Calculate the circumference using the formula C = 2πr.', 'Record your findings in a table.'] }] },
            { name: 'Area and Perimeter', videos: [{ title: 'Area and Perimeter', description: 'Learn how to calculate the area and perimeter of different shapes.', videoId: 'Xk-Py5A14A4', level: 'Intermediate' }], projects: [{ title: 'Design a Dream Room', description: 'Design the floor plan for your dream room and calculate its area and perimeter.', tasks: ['Draw the floor plan on graph paper.', 'Calculate the area and perimeter.', 'Present your design to the class.'] }] },
            { name: 'Volume and Surface Area', videos: [{ title: 'Volume and Surface Area', description: 'Learn how to calculate the volume and surface area of 3D shapes.', videoId: 'qJwecTgce6c', level: 'Advanced' }], projects: [{ title: 'Build a 3D Shape', description: 'Build a 3D shape using cardboard or other materials and calculate its volume and surface area.', tasks: ['Choose a 3D shape.', 'Build a model of the shape.', 'Measure its dimensions.', 'Calculate the volume and surface area.'] }] }
          ] } ] },
        { name: 'Statistics', subTopics: [ { name: 'Data and Statistics', lessons: [
            { name: 'Collecting Data', videos: [{ title: 'Methods of Data Collection', description: 'Learn about surveys, observations, and experiments.', videoId: '7-6-p2xnfYc', level: 'Beginner' }], projects: [{ title: 'Design a Survey', description: 'Design a survey to collect data about a topic of interest.', tasks: ['Choose a topic.', 'Write clear and unbiased questions.', 'Administer the survey to your classmates.', 'Collect the data.'] } ] }] },
            { name: 'Organizing Data', videos: [{ title: 'Tally Charts and Frequency Tables', description: 'Learn how to organize data using tally charts and frequency tables.', videoId: 'GvIm-qJd-48', level: 'Beginner' }], projects: [{ title: 'Organize Your Survey Data', description: 'Organize the data you collected from your survey into a frequency table.', tasks: ['Create a frequency table.', 'Tally the responses to each question.', 'Summarize the results.'] }] },
            { name: 'Displaying Data', videos: [{ title: 'Bar Graphs and Line Graphs', description: 'Learn how to display data using bar graphs and line graphs.', videoId: 'kKKM8Y-u7ds', level: 'Intermediate' }], projects: [{ title: 'Graph Your Survey Data', description: 'Create a bar graph or line graph to display the results of your survey.', tasks: ['Choose the appropriate type of graph.', 'Draw and label the graph.', 'Present your graph to the class.'] }] },
            { name: 'Interpreting Data', videos: [{ title: 'Reading Graphs', description: 'Learn how to read and interpret data from graphs.', videoId: 'fvOmaf2GfCY', level: 'Intermediate' }], projects: [{ title: 'Analyze a Graph', description: 'Find a graph in a newspaper or online and analyze the information it presents.', tasks: ['Find a graph.', 'Identify the main message of the graph.', 'Write a short summary of your analysis.'] }] },
            { name: 'Measures of Central Tendency', videos: [{ title: 'Mean, Median, and Mode', description: 'Learn how to calculate the mean, median, and mode of a data set.', videoId: 'B1HEzNTGeZ4', level: 'Advanced' }], projects: [{ title: 'Analyze a Data Set', description: 'Calculate the mean, median, and mode for a given data set.', tasks: ['Find a data set.', 'Calculate the mean, median, and mode.', 'Explain what each measure tells you about the data.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 8',
      topics: [
        { name: 'Algebra', subTopics: [ { name: 'Algebra', lessons: [
            { name: 'Linear Equations', videos: [{ title: 'Solving Linear Equations', description: 'A step-by-step guide to solving linear equations.', videoId: '9e-KKa1_4v8', level: 'Intermediate' }], projects: [{ title: 'Real-World Algebra Problems', description: 'Find and solve real-world problems using algebra.', tasks: ['Identify a real-world scenario.', 'Formulate an algebraic equation.', 'Solve the equation.', 'Explain the meaning of your solution.'] }] },
            { name: 'Algebraic Expressions', videos: [{ title: 'Introduction to Algebraic Expressions', description: 'Learn the basics of algebraic expressions.', videoId: 'v-6MShC82ow', level: 'Beginner' }], projects: [{ title: 'Create Your Own Expressions', description: 'Create and simplify your own algebraic expressions.', tasks: ['Create five expressions.', 'Simplify each expression.', 'Challenge a classmate to solve them.'] }] },
            { name: 'Inequalities', videos: [{ title: 'Solving Inequalities', description: 'Learn how to solve and graph inequalities.', videoId: '0X-bMeIN53I', level: 'Intermediate' }], projects: [{ title: 'Real-World Inequalities', description: 'Find and solve real-world problems involving inequalities.', tasks: ['Identify a real-world scenario.', 'Formulate an inequality.', 'Solve the inequality.', 'Graph the solution.'] }] },
            { name: 'Simplifying Expressions', videos: [{ title: 'Simplifying Algebraic Expressions', description: 'Learn how to simplify expressions by combining like terms.', videoId: '3NHSwiv_p4E', level: 'Intermediate' }], projects: [{ title: 'Expression Simplification Race', description: 'Race against a classmate to simplify a list of expressions.', tasks: ['Create a list of expressions.', 'Race to simplify them.', 'Check your answers.'] }] },
            { name: 'Factorization', videos: [{ title: 'Factoring Trinomials', description: 'Learn how to factor trinomials.', videoId: '3p4C-T4T8gE', level: 'Advanced' }], projects: [{ title: 'Factorization Puzzles', description: 'Create and solve factorization puzzles.', tasks: ['Create five puzzles.', 'Challenge a classmate to solve them.'] }] },
          ] } ] },
        { name: 'Statistics & Probability', subTopics: [ { name: 'Statistics and Probability', lessons: [
            { name: 'Data Collection and Representation', videos: [{ title: 'Data Representation', description: 'Learn how to represent data using bar graphs, line graphs, and pie charts.', videoId: 'u-ORp5h2e-k', level: 'Beginner' }], projects: [{ title: 'Class Survey', description: 'Conduct a survey on a topic of your choice and represent the data in a graph.', tasks: ['Choose a survey topic.', 'Collect data from your classmates.', 'Create a bar graph or pie chart to represent the data.', 'Present your findings to the class.'] }] },
            { name: 'Measures of Central Tendency', videos: [{ title: 'Mean, Median, and Mode', description: 'Learn how to calculate the mean, median, and mode of a data set.', videoId: 'B1HEzNTGeZ4', level: 'Intermediate' }], projects: [{ title: 'Analyze Class Test Scores', description: 'Calculate the mean, median, and mode of a set of test scores.', tasks: ['Collect a set of test scores.', 'Calculate the mean, median, and mode.', 'Explain what each measure tells you about the data.'] }] },
            { name: 'Introduction to Probability', videos: [{ title: 'Introduction to Probability', description: 'Learn the basic concepts of probability.', videoId: 'KsaP-A-I7uI', level: 'Beginner' }], projects: [{ title: 'Coin Toss Experiment', description: 'Investigate the probability of getting heads or tails when tossing a coin.', tasks: ['Toss a coin 50 times.', 'Record the results.', 'Calculate the experimental probability of getting heads.', 'Compare it to the theoretical probability.'] }] },
            { name: 'Theoretical vs. Experimental Probability', videos: [{ title: 'Theoretical vs. Experimental Probability', description: 'Learn the difference between theoretical and experimental probability.', videoId: '10Lq-4n-l-A', level: 'Intermediate' }], projects: [{ title: 'Dice Roll Experiment', description: 'Compare the theoretical and experimental probability of rolling a specific number on a die.', tasks: ['Roll a die 60 times.', 'Record the results.', 'Calculate the experimental probability of rolling a 6.', 'Compare it to the theoretical probability.'] }] },
            { name: 'Data Analysis and Interpretation', videos: [{ title: 'Interpreting Data', description: 'Learn how to analyze and interpret data from graphs and charts.', videoId: '5-qyj2gjb44', level: 'Advanced' }], projects: [{ title: 'Analyze a Real-World Data Set', description: 'Find a real-world data set and analyze it to draw conclusions.', tasks: ['Find a data set online.', 'Analyze the data using graphs and measures of central tendency.', 'Write a short report summarizing your findings.'] }] }
          ] } ] },
        { name: 'Geometry', subTopics: [ { name: 'Geometry', lessons: [
            { name: 'Properties of 3D Shapes', videos: [{ title: '3D Shapes', description: 'Learn about the properties of 3D shapes like cubes, spheres, and pyramids.', videoId: 'z-h-w-3-d-s', level: 'Beginner' }], projects: [{ title: 'Build 3D Shapes', description: 'Build 3D shapes using nets.', tasks: ['Find or create nets for different 3D shapes.', 'Cut them out and fold them to create the shapes.', 'Describe the properties of each shape.'] } ] }] },
            { name: 'Transformations', videos: [{ title: 'Transformations - Reflection, Rotation, Translation', description: 'Learn about the different types of geometric transformations.', videoId: 't-r-a-n-s', level: 'Intermediate' }], projects: [{ title: 'Create a Tessellation', description: 'Create a tessellation using geometric transformations.', tasks: ['Choose a shape.', 'Use translations, rotations, and reflections to create a repeating pattern.', 'Color your tessellation.'] }] },
            { name: 'Congruence and Similarity', videos: [{ title: 'Congruent and Similar Shapes', description: 'Learn the difference between congruent and similar shapes.', videoId: 'c-o-n-g-r', level: 'Intermediate' }], projects: [{ title: 'Find Similar Shapes', description: 'Find examples of similar shapes in your environment.', tasks: ['Find three pairs of similar shapes.', 'Explain why they are similar.', 'Calculate the scale factor between them.'] }] },
            { name: 'Pythagorean Theorem in 3D', videos: [{ title: 'Pythagorean Theorem in 3D', description: 'Learn how to apply the Pythagorean theorem to 3D shapes.', videoId: 'p-y-t-h-3d', level: 'Advanced' }], projects: [{ title: 'Calculate the Diagonal of a Box', description: 'Calculate the length of the longest diagonal of a box.', tasks: ['Measure the length, width, and height of a box.', 'Use the Pythagorean theorem in 3D to calculate the diagonal.', 'Check your answer by measuring.'] }] },
            { name: 'Circles and Cylinders', videos: [{ title: 'Circles and Cylinders', description: 'Learn about the properties of circles and cylinders.', videoId: 'c-i-r-c-l', level: 'Intermediate' }], projects: [{ title: 'Calculate the Volume of a Can', description: 'Calculate the volume of a cylindrical can.', tasks: ['Measure the radius and height of the can.', 'Use the formula V = πr²h to calculate the volume.', 'Compare your result with the volume listed on the can.'] }] }
          ]
        }
      ]
    },
    {
      grade: 'Grade 9',
      topics: [
        { name: 'Trigonometry & Geometry', subTopics: [ { name: 'Trigonometry', lessons: [
            { name: 'Basic Ratios (Sine, Cosine, Tangent)', videos: [{ title: 'Introduction to Trigonometry', description: 'Learn the basics of sine, cosine, and tangent.', videoId: 'TRIGFYg_N4o', level: 'Beginner' }], projects: [{ title: 'Measure the Height of a Building', description: 'Use trigonometry to measure the height of a tall object.', tasks: ['Learn how to use a clinometer.', 'Measure the angle of elevation.', 'Measure the distance to the object.', 'Calculate the height using trigonometry.'] }] },
            { name: 'The Pythagorean Theorem', videos: [{ title: 'Pythagorean Theorem', description: 'Learn the Pythagorean theorem and how to use it.', videoId: 'GkrgIeunI2U', level: 'Beginner' }], projects: [{ title: 'Prove the Pythagorean Theorem', description: 'Create a visual proof of the Pythagorean theorem.', tasks: ['Research different proofs.', 'Choose one to demonstrate.', 'Create a visual aid.', 'Present your proof to the class.'] }] },
            { name: 'Solving Right-Angled Triangles', videos: [{ title: 'Solving Right Triangles', description: 'Learn how to find the missing sides and angles of a right triangle.', videoId: 'p5K25OAbGvs', level: 'Intermediate' }], projects: [{ title: 'Indirect Measurement', description: 'Use trigonometry to measure the width of a river or the height of a tree.', tasks: ['Choose an object to measure.', 'Use trigonometry to calculate the measurement.', 'Present your findings to the class.'] }] },
            { name: 'Angles of Elevation and Depression', videos: [{ title: 'Angles of Elevation and Depression', description: 'Learn how to solve problems involving angles of elevation and depression.', videoId: 'hM2nJ6Iq5fA', level: 'Intermediate' }], projects: [{ title: 'Real-World Problems', description: 'Find and solve real-world problems involving angles of elevation and depression.', tasks: ['Identify a real-world scenario.', 'Draw a diagram.', 'Solve the problem.', 'Explain your solution.'] }] },
            { name: 'The Unit Circle', videos: [{ title: 'Introduction to the Unit Circle', description: 'Learn the basics of the unit circle.', videoId: '1m9p9iubMLU', level: 'Advanced' }], projects: [{ title: 'Create a Unit Circle Diagram', description: 'Create a detailed diagram of the unit circle.', tasks: ['Draw the unit circle.', 'Label the angles and coordinates.', 'Explain the relationship between the unit circle and trigonometry.'] }] },
          ] }, { name: 'Coordinate Geometry', lessons: [
            { name: 'The Coordinate Plane', videos: [{ title: 'The Coordinate Plane', description: 'An introduction to the Cartesian coordinate plane.', videoId: 'h-3-g-8-c-2', level: 'Beginner' }], projects: [{ title: 'Plotting Points', description: 'Plot a series of points to create a picture.', tasks: ['Create a list of coordinates.', 'Plot the points on a coordinate plane.', 'Connect the dots to reveal the picture.'] } ] },
            { name: 'Distance Formula', videos: [{ title: 'The Distance Formula', description: 'Learn how to find the distance between two points on a coordinate plane.', videoId: 'd-i-s-t-a', level: 'Intermediate' }], projects: [{ title: 'Calculate the Distance', description: 'Calculate the distance between two cities on a map using their coordinates.', tasks: ['Find the coordinates of two cities.', 'Use the distance formula to calculate the distance.', 'Compare your answer to the actual distance.'] }] },
            { name: 'Midpoint Formula', videos: [{ title: 'The Midpoint Formula', description: 'Learn how to find the midpoint of a line segment.', videoId: 'm-i-d-p-t', level: 'Intermediate' }], projects: [{ title: 'Find the Center', description: 'Find the center of a circle given the coordinates of two points on its diameter.', tasks: ['Find the coordinates of two points on the diameter.', 'Use the midpoint formula to find the center.', 'Draw the circle.'] }] },
            { name: 'Slope of a Line', videos: [{ title: 'Slope of a Line', description: 'Learn how to calculate the slope of a line.', videoId: 's-l-o-p-e', level: 'Intermediate' }], projects: [{ title: 'Investigate Slopes', description: 'Investigate the slopes of parallel and perpendicular lines.', tasks: ['Graph two parallel lines and calculate their slopes.', 'Graph two perpendicular lines and calculate their slopes.', 'Describe the relationship between the slopes.'] }] },
            { name: 'Equations of Lines', videos: [{ title: 'Equations of Lines', description: 'Learn about the slope-intercept and point-slope forms of linear equations.', videoId: 'e-q-u-a-t', level: 'Advanced' }], projects: [{ title: 'Write the Equation of a Line', description: 'Write the equation of a line given two points on the line.', tasks: ['Find the slope of the line.', 'Use the point-slope form to write the equation.', 'Convert the equation to slope-intercept form.'] }] }
          ] } ] },
        { name: 'Algebra & Functions', subTopics: [ { name: 'Functions', lessons: [
            { name: 'Introduction to Functions', videos: [{ title: 'What is a Function?', description: 'An introduction to the concept of functions in mathematics.', videoId: '52tpYl2t3wU', level: 'Beginner' }], projects: [{ title: 'Real-World Functions', description: 'Identify and describe real-world examples of functions.', tasks: ['Find three real-world examples of functions.', 'Describe the input and output for each function.', 'Explain why each example is a function.'] }] },
            { name: 'Linear Functions', videos: [{ title: 'Linear Functions', description: 'Learn about linear functions and their graphs.', videoId: 'g-w-p-4-c-8', level: 'Intermediate' }], projects: [{ title: 'Graphing Linear Equations', description: 'Graph linear equations by creating a table of values.', tasks: ['Choose three linear equations.', 'Create a table of values for each equation.', 'Graph each equation on a coordinate plane.'] }] },
            { name: 'Quadratic Functions', videos: [{ title: 'Introduction to Quadratic Functions', description: 'Learn about quadratic functions and their graphs (parabolas).', videoId: 'm-p-g-0-c-4', level: 'Advanced' }], projects: [{ title: 'Graphing Parabolas', description: 'Graph quadratic functions and identify their key features.', tasks: ['Choose three quadratic functions.', 'Graph each function.', 'Identify the vertex, axis of symmetry, and intercepts for each graph.'] }] },
            { name: 'Graphing Functions', videos: [{ title: 'How to Graph Functions', description: 'A general guide to graphing different types of functions.', videoId: 's-p-g-0-c-4', level: 'Intermediate' }], projects: [{ title: 'Function Graphing Portfolio', description: 'Create a portfolio of graphs for different types of functions.', tasks: ['Choose five different functions.', 'Graph each function.', 'Describe the key features of each graph.'] }] },
            { name: 'Function Notation', videos: [{ title: 'Function Notation', description: 'Learn how to use function notation.', videoId: 't-q-9-8-g-o', level: 'Beginner' }], projects: [{ title: 'Evaluating Functions', description: 'Practice evaluating functions for different input values.', tasks: ['Create five functions.', 'Evaluate each function for three different input values.', 'Check your answers with a partner.'] }] }
          ] } ] }
      ]
    }
  ]
};

export const categories: CategoryWithGrades[] = [sciences, languages, math];
